Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 100
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 15
Metrics/ParameterLists:
  Max: 10
Metrics/ModuleLength:
  Max: 250
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false